/**
 * Type definitions matching the BestBill API schemas.
 * Generated by hand from src/bestbill/api/schemas.py and core/models.py.
 */

// ── Enums ──────────────────────────────────────────────────────────────────

export type PriceType = 'fixed' | 'variable'
export type OfferSource = 'placet' | 'mlibero' | 'custom'
export type BandStructure = 'mono' | 'f1f2f3' | 'f1f23'
export type Residency = 'resident' | 'non_resident'

export type BreakEvenStatus = 'cheaper_below' | 'never_cheaper' | 'always_cheaper'

export type SupplierNameSource = 'arera' | 'placet' | 'domain' | 'vat'

// ── Health / Meta ──────────────────────────────────────────────────────────

export interface Health {
  status: 'ok'
  catalog_loaded: boolean
  snapshot_date: string | null
  catalog_age_days: number | null
}

export interface CatalogCounts {
  included: number
  included_by_source: Record<string, number>
  excluded: number
  excluded_by_reason: Record<string, number>
}

export interface CatalogSource {
  name: string
  url: string | null
  licence: string | null
  file_date: string | null
}

export interface CatalogMeta {
  snapshot_date: string
  age_days: number
  stale: boolean
  counts: CatalogCounts
  sources: CatalogSource[]
  licence: string | null
  attribution: string
}

// ── Sample ─────────────────────────────────────────────────────────────────

export interface SampleMonth {
  month: string // YYYY-MM
  kwh: number
}

export interface SampleHousehold {
  location: string
  description: string
  months: SampleMonth[]
}

// ── Comuni ─────────────────────────────────────────────────────────────────

export interface Comune {
  codice: string // 6-digit ISTAT code
  nome: string
  sigla_provincia: string
  regione: string
}

// ── Compare Request ────────────────────────────────────────────────────────

export interface MonthInput {
  month: string // YYYY-MM
  kwh: number
  f1?: number | null
  f2?: number | null
  f3?: number | null
}

export interface CompareFilters {
  price_type?: PriceType | null
  source?: 'placet' | 'mlibero' | null
}

export type Scenario = Historical | Scaled | Flat

export interface Historical {
  kind: 'historical'
}

export interface Scaled {
  kind: 'scaled'
  factor: number
}

export interface Flat {
  kind: 'flat'
  value: number
}

export interface CompareRequest {
  consumption: MonthInput[] // exactly 12
  residency: Residency
  istat_comune?: string | null
  committed_power_kw?: number
  scenario: Scenario
  filters: CompareFilters
  top_n?: number
}

// ── Compare Response ───────────────────────────────────────────────────────

export interface CostBreakdown {
  energy: number
  fixed_fees: number
  per_kwh_extras: number
  power_fee: number
  dispatching: number
  one_off: number
  discounts: number
  total: number
}

export interface Discount {
  name: string
  description: string
  validity: string
  conditional: boolean
  amount: number
  unit: string
  applies_before_vat: boolean
  consumption_from_kwh: number | null
  consumption_to_kwh: number | null
  duration_months: number | null
}

export interface ResultItem {
  offer_id: string
  rank: number
  supplier: string
  name: string
  supplier_vat: string | null
  supplier_name_source: SupplierNameSource | null
  url: string | null
  source: OfferSource
  price_type: PriceType
  band_structure: BandStructure
  valid_from: string | null
  valid_to: string | null
  cost_eur: number
  delta_vs_best_eur: number
  eur_per_kwh_effective: number
  breakdown: CostBreakdown
  break_even_pun_eur_kwh: number | null
  break_even_status: BreakEvenStatus | null
  one_off_fee_eur: number
  conditional_discounts: Discount[]
  dispatching_is_standard_estimate: boolean
}

export interface Assumptions {
  period_start: string
  period_end: string
  pun_months_used: Record<string, number>
  substituted_pun_months: string[]
  band_split_source: 'user' | 'standard'
  scenario: Scenario
  statement: string
  committed_power_kw: number
  residency: Residency
  istat_comune: string | null
  cost_label: string
}

export interface CompareResponse {
  snapshot_date: string
  assumptions: Assumptions
  total_eligible: number
  total_matching: number
  results: ResultItem[]
  excluded_count: number
  excluded_by_reason: Record<string, number>
}

// ── Error ──────────────────────────────────────────────────────────────────

export interface ValidationErrorResponse {
  detail: Array<{ field: string; message: string }>
}

export interface ErrorResponse {
  detail: string
}

// ── API Client ─────────────────────────────────────────────────────────────

const API_BASE = import.meta.env.VITE_API_BASE || 'https://bestbill-api.onrender.com'

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const url = `${API_BASE}${path}`
  const res = await fetch(url, {
    ...init,
    headers: {
      'Content-Type': 'application/json',
      ...init?.headers,
    },
  })
  if (!res.ok) {
    const body = await res.json().catch(() => null)
    const detail = body?.detail
    const message = typeof detail === 'string'
      ? detail
      : Array.isArray(detail)
        ? detail.map((e: { field: string; message: string }) => `${e.field}: ${e.message}`).join(' | ')
        : `Errore del server (${res.status})`
    throw new Error(message)
  }
  return res.json()
}

export const apiClient = {
  health: () => api<Health>('/api/health'),
  catalogMeta: () => api<CatalogMeta>('/api/catalog/meta'),
  sample: () => api<SampleHousehold>('/api/sample'),
  comuni: (q: string) => api<Comune[]>(`/api/comuni?q=${encodeURIComponent(q)}`),
  compare: (body: CompareRequest) => api<CompareResponse>('/api/compare', { method: 'POST', body: JSON.stringify(body) }),
}
