/**
 * Type definitions matching the BestBill API schemas.
 * Generated by hand from src/bestbill/api/schemas.py and core/models.py.
 */

// ── Enums ──────────────────────────────────────────────────────────────────

export type PriceType = 'fixed' | 'variable'
export type OfferSource = 'placet' | 'mlibero'
export type BandStructure = 'mono' | 'f1f2f3' | 'f1f23'
export type Residency = 'resident' | 'non_resident'

export type BreakEvenStatus = 'cheaper_below' | 'never_cheaper' | 'always_cheaper'

export type SourceFilter = 'placet' | 'mlibero'
export type DiscountValidity = 'on_entry' | 'within_12_months' | 'beyond_12_months'
export type DiscountUnit =
  | 'eur_year'
  | 'eur_kw_year'
  | 'eur_kwh'
  | 'eur_smc'
  | 'eur_one_off'
  | 'percent'

export type SupplierNameSource = 'arera' | 'placet' | 'domain' | 'vat'

// ── Health / Meta ──────────────────────────────────────────────────────────

export interface Health {
  status: 'ok'
  catalog_loaded: boolean
  snapshot_date: string | null
  catalog_age_days: number | null
}

export interface CatalogCounts {
  included: number
  included_by_source: Record<string, number>
  excluded: number
  excluded_by_reason: Record<string, number>
}

export interface CatalogSource {
  name: string
  url: string | null
  licence: string | null
  file_date: string | null
}

export interface CatalogMeta {
  snapshot_date: string
  age_days: number
  stale: boolean
  counts: CatalogCounts
  sources: CatalogSource[]
  licence: string | null
  attribution: string
}

// ── Sample ─────────────────────────────────────────────────────────────────

export interface SampleMonth {
  month: string // YYYY-MM
  kwh: number
}

export interface SampleHousehold {
  location: string
  description: string
  months: SampleMonth[]
}

// ── Comuni ─────────────────────────────────────────────────────────────────

export interface Comune {
  codice: string // 6-digit ISTAT code
  nome: string
  sigla_provincia: string
  regione: string
}

// ── Compare Request ────────────────────────────────────────────────────────

export interface MonthInput {
  month: string // YYYY-MM
  kwh: number
  f1?: number | null
  f2?: number | null
  f3?: number | null
}

export interface CompareFilters {
  price_type?: PriceType | null
  source?: SourceFilter | null
  /** Keep offers whose duration is at least / at most this many months.
   *  When either is set, offers with an unspecified duration are excluded by the server. */
  min_duration_months?: number | null
  max_duration_months?: number | null
}

export type Scenario = Historical | Scaled | Flat

export interface Historical {
  kind: 'historical'
}

export interface Scaled {
  kind: 'scaled'
  factor: number
}

export interface Flat {
  kind: 'flat'
  value: number
}

export interface CompareRequest {
  consumption: MonthInput[] // exactly 12
  residency: Residency
  istat_comune?: string | null
  committed_power_kw?: number // > 0, <= 30
  scenario?: Scenario
  filters?: CompareFilters
  top_n?: number // 1..200
  /** Skip this many matching results (pagination). */
  offset?: number
  /** Case/accent-insensitive match on supplier or offer name. Applied after ranking: ranks do not change. */
  search?: string | null
}

// ── Compare Response ───────────────────────────────────────────────────────

export interface CostBreakdown {
  energy: number
  fixed_fees: number
  per_kwh_extras: number
  power_fee: number
  dispatching: number
  one_off: number
  discounts: number
  total: number
}

export interface Discount {
  name: string
  description: string
  validity: DiscountValidity
  conditional: boolean
  amount: number
  unit: DiscountUnit
  applies_before_vat: boolean
  consumption_from_kwh: number | null
  consumption_to_kwh: number | null
  duration_months: number | null
}

/** An unconditional discount that is counted in breakdown.discounts. */
export interface AppliedDiscount {
  name: string
  /** What is actually credited in the 12-month estimate (> 0). */
  amount_in_estimate_eur: number
  /** The total the supplier declares; null when it is not a fixed euro amount (e.g. a percentage). */
  declared_amount_eur: number | null
  unit: DiscountUnit
  /** Set when the bonus is paid in instalments: total months over which it is paid. */
  instalment_months: number | null
  instalment_amount_eur: number | null
}

export type EnergyPriceKind = 'fixed' | 'pun_spread'

export interface ResultItem {
  offer_id: string
  rank: number
  supplier: string
  name: string
  supplier_vat: string | null
  supplier_name_source: SupplierNameSource | null
  url: string | null
  source: OfferSource
  price_type: PriceType
  band_structure: BandStructure
  valid_from: string | null
  valid_to: string | null
  cost_eur: number
  delta_vs_best_eur: number
  /** Total cost ÷ kWh: includes CCV, dispatching and other costs. */
  eur_per_kwh_effective: number
  /** Advertised energy unit price (before discounts, no fixed fees). For 'pun_spread' it is only the spread over PUN. */
  energy_price_eur_kwh: number
  energy_price_kind: EnergyPriceKind
  /** Energy price after unconditional discounts that act on the energy price (same base as energy_price_eur_kwh).
   *  May be missing on older API versions: fall back to energy_price_eur_kwh. */
  energy_price_after_discounts_eur_kwh?: number
  /** % discount between listed and after-discount price (1 decimal); null when no such discount. */
  energy_discount_pct?: number | null
  breakdown: CostBreakdown
  break_even_pun_eur_kwh: number | null
  break_even_status: BreakEvenStatus | null
  one_off_fee_eur: number
  conditional_discounts: Discount[]
  /** Unconditional discounts counted in breakdown.discounts. Missing on older API versions (unknown):
   *  fall back to breakdown.discounts > 0. */
  applied_discounts?: AppliedDiscount[]
  /** Contract / price-lock duration. null + duration_open_ended=false = unknown. May be missing on older API versions. */
  duration_months?: number | null
  duration_open_ended?: boolean
}

export interface Assumptions {
  period_start: string
  period_end: string
  /** Keys are ISO dates (first of month, YYYY-MM-01). */
  pun_months_used: Record<string, number>
  substituted_pun_months: string[] // ISO dates
  band_split_source: 'user' | 'standard'
  scenario: Scenario
  statement: string
  committed_power_kw: number
  residency: Residency
  istat_comune: string | null
  cost_label: string
}

export interface CompareResponse {
  snapshot_date: string
  assumptions: Assumptions
  total_eligible: number
  /** Offers matching the filters (ignores search). */
  total_matching: number
  /** Filtered offers matching `search`; null when no search. May be missing on older API versions. */
  search_matching?: number | null
  offset?: number
  results: ResultItem[]
  excluded_count: number
  excluded_by_reason: Record<string, number>
}

// ── Error ──────────────────────────────────────────────────────────────────

export interface ValidationErrorResponse {
  detail: Array<{ field: string; message: string }>
}

export interface ErrorResponse {
  detail: string
}
